spring:
  cloud:
    vault:
      uri: http://vault.vault:8200
      kv:
        enabled: true
        application-name: invntree-app
        backend: kv
      authentication: kubernetes
      kubernetes:
        role: role-test

  config:
    import: vault://kv/invntree-app