spring:
  cloud:
    config:
      server:
        git:
          uri: file:${user.dir}/configs/config-repo
          default-label: master
          force-pull: true
    vault:
      scheme: http
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: kv
        application-name: invntree-app
        profile-separator: '/'
        profiles: vault

  config:
    import: vault://kv/invntree-app