spring:
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      host: 127.0.0.1
      port: 8200
      authentication: token
      token: ${VAULT_TOKEN}
      kv:
        application-name: invntree-app
        enabled: true
        backend: kv

  config:
    import: vault://kv/invntree-app

